currency:
  available:
    - "RUB"
cost:
  rub:
    perKg: 100
    minimal: 350
volume:
  perCubicMeter: 10000
  maxDimension: 1500
distance:
  baseRateDistanceKilometers: 450
  minLatitude: 45
  maxLatitude: 65
  minLongitude: 30
  maxLongitude: 96